POST http://localhost:2222/register
Content-Type: application/json

{
  "weight": 75,
  "height": 175,
  "year_born": 2000,
  "sex": 0.69,
  "email": "sergej.stokurew@vladivostok.ru",
  "password_hash": "aslkdjflkasjdflkjdf",
  "desired_carbs": 15.4,
  "desired_proteins": 15.4,
  "desired_fats": 15.4,
  "desired_saturated_fats": 15.4,
  "desired-fiber": 15.4
}
